sudo: required
services:
  - docker

before_install:
  - docker build -t victorhvargas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true victorhvargas/docker-react npm run test

# language: generic